<?php

declare(strict_types=1);


namespace OnixSystemsPHP\HyperfAuth\Test\Cases\Services;

use Hyperf\Database\Model\ModelNotFoundException;
use OnixSystemsPHP\HyperfAuth\Model\UserSocialite;
use OnixSystemsPHP\HyperfAuth\Repository\UserSocialiteRepository;
use OnixSystemsPHP\HyperfAuth\Service\DeleteSocialiteService;
use OnixSystemsPHP\HyperfAuth\Test\Cases\AppTest;

/**
 * @internal
 * @coversNothing
 */
class DeleteSocialiteServiceTest extends AppTest
{
    protected function setUp(): void
    {
        $this->createContainer([['name' => 'get']]);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testMain()
    {
        $userSocialite = new UserSocialite([
            'id' => 1,
            'email' => 'test@test.com',
            'provider_id' => 21,
            'provider_name' => 'google',
            'user_id' => 2,
        ]);

        $service = $this->getService($userSocialite, 1);
        $service->run('fakeName', 1);
        $this->assertTrue(true);
    }

    public function testWhereUserIsEmpty()
    {
        $service = $this->getService(null, 0);
        try {
            $service->run('fakeName', 1);
            $this->fail();
        } catch (ModelNotFoundException) {
            $this->assertTrue(true);
        }
    }

    protected function getService(?UserSocialite $userSocialite, int $eventCount): DeleteSocialiteService
    {
        $userSocialiteRepository = $this->createMock(UserSocialiteRepository::class);
        $userSocialiteRepository->method('delete')->willReturn(true);
        if ($userSocialite) {
            $userSocialiteRepository->method('getByUserProvider')->willReturn($userSocialite);
        } else {
            $userSocialiteRepository->method('getByUserProvider')->willThrowException(new ModelNotFoundException());
        }

        return new DeleteSocialiteService(
            $userSocialiteRepository,
            null,
            $this->getEventDispatcherMock($eventCount)
        );
    }
}
